name: CI/CD with Linting and Formatting
on: [push]
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npx prettier . --write
